model:
  checkpoint_path: "../final_model/DINOv2_custom.pth"  # Updated to your actual model
  device: "cuda"
  similarity_threshold: 0.8

data:
  image_size: [518, 518]
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

output:
  save_dir: "test_results"
  visualization_dir: "test_results/visualizations"
  report_dir: "test_results/reports"

visualization:
  max_images_per_row: 8
  dpi: 300
  font_size: 10
  title_size: 12
  score_color:
    high: "green"
    medium: "orange"
    low: "red"
