availableSecrets:
  secretManager:
    - versionName: projects/dash-realty-agent-portal/secrets/dash-realty-agent-portal-ba916c514fa4/versions/latest
      env: GOOGLE_APPLICATION_CREDENTIALS_JSON

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS_JSON']
    args:
      - '-c'
      - |
        # Move into the Dockerfile directory
        cd PropertySimilarity_v1/api

        # Write secret key to file
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > sa_key.json
        export GOOGLE_APPLICATION_CREDENTIALS=sa_key.json

        # Authenticate
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project dash-realty-agent-portal

        # Build and push Docker image
        docker build -t us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-vertex-fixed .
        docker push us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-vertex-fixed

        # Upload model to Vertex AI
        gcloud ai models upload \
          --region=us-central1 \
          --display-name=property-comparison-api \
          --container-image-uri=us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-vertex-fixed \
          --container-ports=8080 \
          --container-health-route=/health \
          --container-predict-route=/predict \
          --artifact-uri=gs://property-comparison-model/

        # Deploy to Vertex endpoint
        gcloud ai endpoints deploy-model 8090871761710612480 \
          --region=us-central1 \
          --model=2418225192200306688 \
          --display-name=property-comparison-api-deployment \
          --machine-type=n1-standard-4 \
          --accelerator=type=NVIDIA_TESLA_A100,count=1 \
          --traffic-split=0=100 \
          --service-account=vertex-ai-access-398@dash-realty-agent-portal.iam.gserviceaccount.com
