steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-vertex-fixed',
        '.'
      ]
    dir: 'PropertySimilarity_v1/api'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-vertex-fixed'
      ]

  # Step 3: Authenticate with service account JSON secret
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS_JSON']
    args:
      - '-c'
      - |
        echo "$$GOOGLE_APPLICATION_CREDENTIALS_JSON" > sa_key.json
        export GOOGLE_APPLICATION_CREDENTIALS=sa_key.json

        gcloud auth activate-service-account --key-file=sa_key.json
        gcloud config set project dash-realty-agent-portal

  # Step 4: Deploy to Cloud Run with NVIDIA L4 GPU
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy compare-property \
          --image=us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-vertex-fixed \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=vertex-ai-access-398@dash-realty-agent-portal.iam.gserviceaccount.com \
          --cpu=4 \
          --memory=16Gi \
          --timeout=300s \
          --port=8080 \
          --max-instances=3 \
          --execution-environment=gen2 \
          --update-secrets=GOOGLE_APPLICATION_CREDENTIALS_JSON=projects/464994061323/secrets/dash-comps-puller-ai:latest \
          --labels=cloud.googleapis.com/accelerator=nvidia-l4

availableSecrets:
  secretManager:
    - versionName: projects/464994061323/secrets/dash-comps-puller-ai/versions/latest
      env: GOOGLE_APPLICATION_CREDENTIALS_JSON

options:
  logging: CLOUD_LOGGING_ONLY
