availableSecrets:
  secretManager:
    - versionName: projects/464994061323/secrets/dash-comps-puller-ai/versions/latest
      env: GOOGLE_APPLICATION_CREDENTIALS_JSON

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS_JSON']
    args:
      - '-c'
      - |
        # Navigate to the API directory
        cd PropertySimilarity_v1/api

        # Write secret (service account JSON) to a key file
        echo "$$GOOGLE_APPLICATION_CREDENTIALS_JSON" > sa_key.json
        export GOOGLE_APPLICATION_CREDENTIALS=sa_key.json

        # Authenticate with the service account
        gcloud auth activate-service-account --key-file=$$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project dash-realty-agent-portal

        # Build and push Docker image to Artifact Registry
        docker build -t us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-cloudrun .
        docker push us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-cloudrun

        # Deploy to Cloud Run (not Vertex AI)
        gcloud run deploy comapre-property \
          --image=us-central1-docker.pkg.dev/dash-realty-agent-portal/property-api-repo-us-central1/property-api-cloudrun \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --memory=4Gi \
          --cpu=2 \
          --service-account=vertex-ai-access-398@dash-realty-agent-portal.iam.gserviceaccount.com \
          --port=8080
